name: Create Release
on: [push]

env:
  fritz_deploy_repo: swift-framework
  tag: 5.3.1
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Swift Framework
        uses: actions/checkout@v2

      # - name: Create Release


      - name: Trigger release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ secrets.REPO_NAME }}
          event-type: sdk-release
          # client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
