name: Deploy Jazzy docs
on:
  push:
    tags: "*"
env:
  BUILD_DIR: /tmp/build


jobs:
  ios-docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout swift-framework
        uses: actions/checkout@v2
      - name: Set release tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build . -t jazzy -f deploy/JazzyDockerfile
      - name: Run build
        run: |
          mkdir $BUILD_DIR
          docker run \
            --volume $BUILD_DIR:/build \
            jazzy deploy/build.sh
      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
        run: |
          set -eo pipefail
          pip install wheel
          pip install awscli
          deploy/deploy.sh /tmp/build $TAG
